# Generated by Django 3.1.6 on 2022-02-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20220205_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='Situation',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='option',
            field=models.CharField(choices=[('It happened to me', 'It happened to me'), ('It was already like that', 'It was already like that')], max_length=200),
        ),
        migrations.AlterField(
            model_name='call',
            name='reason',
            field=models.CharField(choices=[('Delete patient', 'Delete patient'), ('System problems', 'System problems'), ('Others', 'Others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='call',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='You will take responsibility'),
        ),
    ]
