# Generated by Django 3.1.6 on 2022-02-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220205_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
    ]
